design the front-end page
FACG6/wallet pull request #74
Opened 2019-03-20 09:19 UTC by mohammedmh

relates 32

2019-03-20 09:32 UTC, KhaderMurtaja approved these changes

2019-03-20 12:58 UTC, KhaderMurtaja requested changes
change the body and give it to main section which defined in views-partials

2019-03-22 13:16 UTC, engshorouq commented on public/css/transactions.css
> +const { sign } = require('jsonwebtoken');
I don't understand the file name is ``` public/css/transactions.css ```
and the content of file is create cookie copy from old project https://github.com/FACG6/CMSPosts/blob/master/src/controllers/middleware/createCookie.js
please write your own function

2019-03-22 13:17 UTC, engshorouq commented on public/js/loginDom.js
> +
where the validation in front end to prevent empty data and other things

2019-03-22 13:20 UTC, engshorouq commented on public/js/loginDom.js
> +        window.location.href = '/';
as I know after ensure from the email and password we need to go to ``` /my-wallet ```

2019-03-22 13:25 UTC, engshorouq commented on src/views/login.hbs
> +        <input type="email" class="email" id="email" placeholder="Email" required>
you do not need required attribute in html element because in dom you add event Lister in the button the the require not work here

2019-03-22 13:26 UTC, engshorouq requested changes
ensure from the name of files and the content please

2019-03-27 10:20 UTC, closed without merging