Sign up back end
FACG6/wallet pull request #80
Opened 2019-03-20 13:49 UTC by KhaderMurtaja

Relates #31 
## Edits:
modify **`index.js`** file in controllers folder by adding :
 -  signup route and pass the necessary middleware.
 - add get and post controllers in signup.js

##  New Features : 
- add **`validateIncomeData`** middleware to check if incoming data is valid or not.
- add **`checkEmail`** middleware to check if incoming email is already used or not.
- add **`hashPassword`** middleware to to hash the incoming password
- add **`addUser`** middleware to execute the insert user query.

2019-03-20 14:09 UTC, engshorouq commented on package.json
> +    "bcrypt": "^3.0.5",
the bcryptjs already insatll why don't use it !!!!!!!!!!!!!!!!!

2019-03-20 14:51 UTC, asmaa-ezz requested changes

2019-03-20 14:51 UTC, asmaa-ezz commented on package.json
> +    "bcrypt": "^3.0.5",
bcrypt is better than bcryptjs

2019-03-20 14:51 UTC, asmaa-ezz commented on src/controllers/index.js
> +router.route('/signup')
I prefer the name in router `/sign-up`

2019-03-20 14:51 UTC, asmaa-ezz commented on src/controllers/index.js
> +
the empty line !!

2019-03-20 14:51 UTC, asmaa-ezz commented on src/controllers/middlewares/addUser.js
> +      res.status(500).send(JSON.stringify({ error: 'Internal Servar Error!!' }));
Question :
Will you do a special page for error 500 ?

2019-03-20 14:51 UTC, asmaa-ezz commented on src/database/queries/checkEmail.js
> +  connection.query('select * from "user" where email=$1', [email]);
the user information is secrecy 
so this query to return info not need 
if the email exist, it return the password in user but no need it

2019-03-20 14:51 UTC, asmaa-ezz commented on src/controllers/middlewares/checkEmail.js
> +  checkEmail.checkEmail(req.body.email)
```suggestion
const checkEmail = require('./../../database/queries/checkEmail');
exports.checkEmailExist = (req, res, next) => {
  checkEmail.checkEmail(req.body.email)
```
Can you replace? 

```javascript
const { checkEmail } = require('./../../database/queries/checkEmail');
exports.checkEmailExist = (req, res, next) => {
  checkEmail(req.body.email)
```

2019-03-20 17:50 UTC, engshorouq commented on src/controllers/middlewares/addUser.js
> +      res.status(500).send(JSON.stringify({ error: 'Internal Servar Error!!' }));
when make fetch , you can not send the error to '500 internal server error' page
fetch just send request and get response and can not make also redirect as i know

2019-03-20 17:54 UTC, engshorouq commented on package.json
> +    "bcrypt": "^3.0.5",
bcrypt ok  is better and fast than bcryptjs but we need use bcryptjs because promise is built in it.

2019-03-21 07:16 UTC, KhaderMurtaja commented on src/controllers/index.js
> +router.route('/signup')
Done

2019-03-21 07:16 UTC, KhaderMurtaja commented on src/controllers/index.js
> +
Solved it

2019-03-21 07:18 UTC, KhaderMurtaja commented on src/controllers/middlewares/checkEmail.js
> +  checkEmail.checkEmail(req.body.email)
Done

2019-03-21 07:24 UTC, KhaderMurtaja commented on src/database/queries/checkEmail.js
> +  connection.query('select * from "user" where email=$1', [email]);
Done

2019-03-21 07:34 UTC, closed without merging