Modify sign up and check js file
FACG6/wallet pull request #82
Opened 2019-03-21 07:34 UTC by KhaderMurtaja

- modify **`index.js`** file and ensure **eslint**.

- modify some **functions' name** in some controllers to make it understandable.

- modify **check email query** to return **unsecured columns**.

2019-03-21 07:49 UTC, mohammedmh approved these changes

2019-03-21 09:06 UTC, IsraaSulaiman approved these changes

2019-03-21 09:10 UTC, asmaa-ezz approved these changes

2019-03-22 11:49 UTC, engshorouq commented on package.json
> +    "test": "NODE_ENV=test tape test/testQueries.js | tap-spec && tape test/testRoutes.js | tap-spec",
if you read the error in Travis is 
```
 /home/travis/build/FACG6/wallet/src/database/dbConnection.js:13
  throw new Error('No Database URL Available'); 
```
that means the Travis can not able to access to database testing url 
if you focus in the line of the script  the first side of script have ``` NODE_ENV=test ``` but the second side does not contain the ``` NODE_ENV=test ``` , also if you focus in ``` dbConnection.js ```  
```
let dbUrl = '';
if (process.env.NODE_ENV === 'pro') {
  dbUrl = process.env.DB_HEROKU_URL;
} else if (process.env.NODE_ENV === 'test') {
  dbUrl = process.env.DB_TESTING_URL;
} else {
  dbUrl = process.env.DB_LOCAL_URL;
}
if (!dbUrl) {
  throw new Error('No Database URL Available');
}
```
the initial value of dbUrl is empty string then the result is error message and the Travis can not able to access to the link of testing

2019-03-22 11:52 UTC, engshorouq commented on src/app.js
> -
put empty line between the core module and local module

2019-03-22 11:54 UTC, engshorouq commented on src/controllers/middlewares/addUser.js
> +const insertUser = require('./../../database/queries/insertUser');
can called it by ```  require('../../database/queries/insertUser'); ```

2019-03-22 12:03 UTC, engshorouq commented on src/controllers/middlewares/hashPassword.js
> +      res.body.password = hash;
OMG !!!!!!!!!!!!!!!!
you put the hashed password in response

2019-03-22 12:04 UTC, engshorouq commented on src/controllers/middlewares/addUser.js
> +  insertUser.insert(username, password, email).then(() => {
you sure the password hashed before insert in database ?????

2019-03-22 12:05 UTC, engshorouq commented on src/controllers/signUp.js
> +  if (req.error) {
from any location or middleware give the request error 
in every middleware you handle error by send ``` res.status(500).send('internal server error') ``` or other error message 
please tell me when the this error appear ??

2019-03-22 12:10 UTC, engshorouq commented on src/controllers/middlewares/checkEmail.js
> +      if (result.rows.length === 0) {
you can but 
```
if(!result.rowCount)
```

2019-03-22 12:12 UTC, engshorouq commented on src/controllers/middlewares/validateIncomeData.js
> +  } else if (!validator.isAlphanumeric(pass)) {
don't try to restrict user especially in password 
the password can contains special character

2019-03-22 12:18 UTC, engshorouq commented on src/database/queries/insertUser.js
> +  connection.query('INSERT INTO "user" (username,password,email) VALUES ($1, $2, $3) returning *', [username, password, email]);
please tell me , you ensure when require this function is work and add in database ???????????
the function must be like this to can deal with promise and execute the query 
```
exports.insert = (username, password, email) => connection.query('INSERT INTO "user" (username,password,email) VALUES ($1, $2, $3) returning *', [username, password, email]);
```
or if you need put bracts to your function 
```
exports.insert = (username, password, email) => {
  return connection.query('INSERT INTO "user" (username,password,email) VALUES ($1, $2, $3) returning *', [username, password, email]);
}
``` 
and apply in all you queries like in  ``` checkEmail.js ```

2019-03-22 13:06 UTC, engshorouq requested changes
Please ensure the data stored in database

2019-03-24 11:45 UTC, engshorouq approved these changes

2019-03-24 17:08 UTC, tomduggan85 commented on src/controllers/middlewares/validateIncomeData.js
> +    req.body.username = username.trim();
@KhaderMurtaja Minor thing, you don't need to trim() here since you already trimmed on line 7 and 9

2019-03-24 17:15 UTC, tomduggan85 commented on src/controllers/signUp.js
> +  res.send({ state: true });
@KhaderMurtaja It might help to have a more descriptive variable name than `state` - I can't tell what `state` is supposed to mean.

2019-03-27 10:21 UTC, closed without merging