Loginbackend
FACG6/wallet pull request #83
Opened 2019-03-21 08:10 UTC by mohammedmh

2019-03-22 10:31 UTC, engshorouq commented on public/js/loginDom.js
> +  console.log('Error from res.error');
rmove all conole log in your code

2019-03-22 10:32 UTC, engshorouq commented on public/js/loginDom.js
> +      console.log('mohammed');
what i understand from this log

2019-03-22 10:34 UTC, engshorouq commented on src/controllers/middlewares/isUser.js
> +const checkUser = require('./../../database/queries/selectUser');
you can make just ``` require('../../database/queries/selectUser'); ```

2019-03-22 10:38 UTC, engshorouq commented on src/controllers/transactions.js
> +exports.post = (req, res) => {
there is no post in transactions just display the transactions about specific category for specific user and plan

2019-03-22 10:40 UTC, engshorouq commented on src/database/dbBuild.js
> -
why delete this line in eslint will give you error , you must put empty line between the require and code

2019-03-22 10:44 UTC, engshorouq commented on src/database/queries/selectSpecificTransaction.js
> +exports.select = () => connection.query('select categories.name , expenses.plan_id , expenses.cat_id , expenses.price , expenses.date , expenses.description from expenses INNER JOIN categories on exp
in this query the task is select the transactions about specific category for specific user and plan 
then there is a condition to select the rows from the database 
and there is a big error her is how make select query and at the end of it make returning ??????????????????????

2019-03-22 10:56 UTC, engshorouq commented on src/database/queries/selectUser.js
> +exports.select = (email, password) => connection.query('select email, password from "user" where email=$1 , password=$2', [email, password]);
the password in database must be hash then the all result will be empty.
the first step must check if the email exist then take the password and comparing it with the password come from the user from the front end if match crate the cookie for this user and go to his profile or his wallet
and there is also big mistake ``` 'select email, password from "user" where email=$1 , password=$2' ```
the several condition in query must but between them or , and

2019-03-22 10:58 UTC, engshorouq commented on public/js/loginDom.js
> +   // create Error message and holder
where the validation in dom , you should make the validation from the front end before go to the back end to prevent empty data and other things

2019-03-22 10:59 UTC, engshorouq commented on src/views/transactions.hbs
> +<h2>transaction.hbs</h2>
what i understand from this line in this file

2019-03-22 11:00 UTC, engshorouq commented on test/testQueries.js
> +const selectUser = require('../src/database/queries/selectUser');
why call the query and you did not make testing for it

2019-03-22 11:02 UTC, engshorouq commented on test/testRoutes.js
> +const selectUser = require('../src/database/queries/selectUser');
why called the query in this file 
this file for test just the routers
when do not use any variable or function delete it please

2019-03-22 11:07 UTC, engshorouq commented on package.json
> -    "validator": "^10.11.0"
why you delete validator ??
other team member use it

2019-03-22 12:23 UTC, engshorouq commented on public/css/signUp.css
> +body {
please do not use html element in your css 
can deal with that by add your main section appropriate min-height

2019-03-22 12:24 UTC, engshorouq commented on src/controllers/login.js
> +  res.send('mohammed');
what i understand from that line ?????

2019-03-22 12:25 UTC, engshorouq commented on src/controllers/middlewares/createCookie.js
> +
why put empty line here 
payload also must contain the name of user

2019-03-22 12:43 UTC, engshorouq commented on package.json
> +    "validator": "^10.11.0"
you install validator module in devDependencies ????
the validator install in dependencies because this module use in our website in validation.
any module need to install it you need to know where you need put it , and you need to know The difference between devDependencies and dependencies, is that devDependencies are modules which are only required during development, while dependencies are modules which are also required at runtime.

2019-03-22 12:53 UTC, engshorouq commented on src/controllers/middlewares/isUser.js
> +        res.send(JSON.stringify({ error: 'Email Already Exists' }));
why send error message when found the email in database
as i know this function for login route 
the first you need to ensure the email exist in database 
  - if not  send error message ``` res.send(JSON.stringify({ error: 'Please ensure from your email or password' })); ```
  - if exist take the password for this email and compare with password come from front end 
       - if true  create cookie and send success message 
       -  but if false send error message ``` res.send(JSON.stringify({ error: 'Please ensure from your email or password' })); ```

2019-03-22 12:56 UTC, engshorouq requested changes
please ensure you understand how can make login in backend

2019-03-24 17:19 UTC, tomduggan85 commented on public/js/loginDom.js
> +  console.log(email, password);
@mohammedmh Don't forget to remove this log 😅

2019-03-24 17:22 UTC, tomduggan85 commented on public/js/loginDom.js
> +    form.removeChild(document.querySelector('.error'));
@mohammedmh Another alternative is to store this element in a variable, and then call parentNode.removeChild to remove it.  It would look like this:
```
const errorEl = document.querySelector('.error');
if (errorEl) {
  errorEl.parentNode.removeChild(errorEl);
}
```
Then, if you changed your dom structure and .error was no longer a direct child of form, this code wouldn't break.

2019-03-24 17:22 UTC, tomduggan85 commented on public/js/loginDom.js
> +  console.log(data);
@mohammedmh and this log too

2019-03-24 17:26 UTC, tomduggan85 commented on src/controllers/middlewares/selectTransactions.js
> +    selectTransaction(req.params.category, req.token.id, req.token.planId)
@mohammedmh Will planId be on the token?  That seems like something that would be passed to the server in perhaps the route instead?

2019-03-24 17:27 UTC, tomduggan85 commented on src/controllers/middlewares/selectTransactions.js
> +      req.row = file.rows;
@mohammedmh It might help to use a more descriptive name when you set this on the request object, like `req.transactions`.

2019-03-24 17:34 UTC, tomduggan85 commented on public/css/signUp.css
> +  color: #8e8e8e;
@mohammedmh If the amount of "common" style rules that you have to include into each page css file (like this placeholder coloring and the `* {` styles) starts to become a lot, you could consider creating a `common.css` file to hold them all.  Right now it's not very much duplicated css, but if it becomes more, that approach might make things easier for you all.

2019-03-24 17:36 UTC, tomduggan85 commented on src/app.js
> +app.set('port', process.env.PORT || 3000);
@mohammedmh my small piece of advice: whenever I make changes to the dev environment like this, I try and remember to tell all of the other people on my team about the change (because it can be easy to miss this when they are reviewing your PR, and it'll affect them once this is merged to master).

2019-03-24 17:43 UTC, tomduggan85 commented on src/controllers/middlewares/selectTransactions.js
> +    selectTransaction(req.params.category, req.token.id, req.token.planId)
@mohammedmh Nevermind, I learned from another PR that the plan is stored as a session cookie.  Sorry about that!

2019-03-26 13:45 UTC, engshorouq approved these changes

2019-03-26 13:53 UTC, engshorouq commented
@IsraaSulaiman  @asmaa-ezz  Please make review

2019-03-26 14:01 UTC, engshorouq commented
@IsraaSulaiman @assmaa-ezz please make review to marge it

2019-03-26 14:20 UTC, IsraaSulaiman approved these changes

2019-03-27 11:38 UTC, merged